name: deploy deployment workflow

on:
    pull_request:
      types: [closed]
      branches:
        - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ubuntu/cicd-pipeline-workshop
            git pull
            mkdir /home/ubuntu/a.txt
            pm2 restart src/server.js


  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to production
        run: echo "Deploy to production successfully!"