name: deploy deployment workflow

on:
    pull_request:
      types: [closed]
      branches:
        - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: deploy to production
        run: echo "deploy to production successfully!"