name: deploy deployment workflow

on:
    pull_request:
      types: [closed]
      branches:
        - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: deploy to production
        run: echo "deploy to production successfully!"
    
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - name: deploy to ec2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ubuntu/cicd-pipeline-workshop
            git pull
            pm2 restart src/server.js