name: deploy deployment workflow

on:
    pull_request:
      types: [opened]
      branches:
        - main
jobs:
  if_test:
    runs-on: ubuntu-latest
    steps:
      - name : Test before deploy
        run: echo "Test before deploy successfully!"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name : Install dependencies
        run: npm install
      - name : Run Tests
        run: ./node_modules/.bin/nyc --reporter=html ./node_modules/.bin/mocha --reporter mochawesome
    #   - name : exit with error if tests fail
    #     run: exit 1
          

  if_merged:
    if: github.event.pull_request.merged == true
    needs: if_test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ubuntu/cicd-pipeline-workshop
            git pull
            mkdir -p /home/ubuntu/d.txt
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
            pm2 restart src/server.js || pm2 start src/server.js




  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: if_merged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to production
        run: echo "Deploy to production successfully!"