name: manual

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hi,  ${{ inputs.logLevel }} "
